### ISSUE TITLE
Setup specific version of external projects

### ISSUE THREAD

**Issue by jucovschi** [KWARC/localmh#191]
I want to use a specific LaTeXML commit (not branch) for the current lmh repository. I tried 
```
lmh setup --reinstall LaTeXML:98fc75e775a23f88449817bdfcb82f3759ac905e
```
but it fails with:
```
Using LaTeXML Version: 98fc75e775a23f88449817bdfcb82f3759ac905e@
fatal: repository '98fc75e775a23f88449817bdfcb82f3759ac905e' does not exist
```

Putting an "@98fc75e775a23f88449817bdfcb82f3759ac905e" fails with
```
Cloning into '/home/cjucovschi/localmh/ext/LaTeXML'...
fatal: Remote branch commit/98fc75e775a23f88449817bdfcb82f3759ac905e not found in upstream origin
Unexpected end of command stream
```

From the documentation is not clear what syntax I should use.

**Comment by kohlhase** [comment]
@tkw1536 could you give this priority please? This is on the critical path to fixing MathHub.info and SMGloM.

**Comment by tkw1536** [comment]
@jucovschi The syntax is: 

```
lmh setup --reinstall LaTeXML:REPOSITORY@BRANCH_OR_TAG
```

So for your example it should be: 
```
lmh setup --reinstall LaTeXML:@98fc75e775a23f88449817bdfcb82f3759ac905e
```

However, 98fc75e775a23f88449817bdfcb82f3759ac905e is neither a branch or a tag. I will try and implement it tomorrow. As a workaround, you can ask @dginev (since its his repository that is used by default) to make a tag pointing to the specific revision or fork the repository and make a tag there.

**Comment by dginev** [comment]
It is probably wise to wait for the 0.8.1 LaTeXML release, and then tag that after I merge with the KWARC fork. If you think you have problems now, wait until your libxml2 binaries get updated... There is a very serious breakage in upstream libxml that Bruce and I are trying to resolve before that libxml release is shipped to more folks.

**Comment by tkw1536** [comment]
Fixed on dev, you can now do 
```
lmh setup --reinstall LaTeXML:@98fc75e775a23f88449817bdfcb82f3759ac905e
```
and it installes the given commit of LaTeXML.
