### ISSUE TITLE
latexml installation fails reliably on a bare-bones machine

### ISSUE THREAD

**Issue by m-iancu** [KWARC/localmh#199]
latexml installation vie lmh always fails because it needs some libraries. 
It might be good if those are added as dependencies to lmh.
As far as I know these include (or are): 
`libxml2-dev`
`libxslt1-dev`
`libgdbm-dev` ? (not 100% sure I remember correctly the name of this one)

**Comment by kohlhase** [comment]
The prerequisites are at http://dlmf.nist.gov/LaTeXML/get.html

**Comment by m-iancu** [comment]
I think lmh does a local installation with cpanm and that takes care of _some_ of those. But, I seem to always have to manually install the ones I mentioned in addition to that. 
Still, @tkw1536 probably knows the details better.

**Comment by kohlhase** [comment]
yes, but that  cpanm does not install the prerequisites. (I think; @deyan knows best) the best way to do this is to install the prerequisites from get.html via the debian packages and then use cpanm.

**Comment by tkw1536** [comment]
@m-iancu The dependencies are listed at https://github.com/KWARC/localmh#ubuntu--debian . 
Last time I checked ```libxml2-dev libxslt-dev libgdbm-dev``` are in there.

**Comment by tkw1536** [comment]
@kohlhase It's @dginev not (at)deyan

**Comment by dginev** [comment]
Rule of thumb is that cpanm can only install Perl dependencies, not external binaries. Some Perl modules carry their C code around with them, but libxml and libxslt are externally required. I thought sane Ubuntu distributions have libxml and libxslt installed by default?

You also need libdb-dev, I don't think we use gdbm for anything (not sure what that is).

**Comment by cmaeder** [comment]
I can confirm that I needed to install `libxslt1-dev` (not the `1`!) and `libgdbm-dev` (`libdb-dev` is not in installed on my Ubuntu 14.04)

**Comment by dginev** [comment]
Hm, thinking about this some more, if cpanm decides to rebuild the Perl wrappers for libxml and libxslt (XML::LibXML and XML::LibXSLT), you indeed need the development headers, so that the compilation can succeed. There might be a way to tell cpanm not to install wrappers already available as debian repositories, but if installing the ```-dev``` headers isn't too big of a problem, that is also ok.

**Comment by tkw1536** [comment]
I believe this is working again now.
