### ISSUE TITLE
installation detection fails when MathHub is a symlink

### ISSUE THREAD

**Issue by tkw1536** [KWARC/localmh#202]
which is a problem for lmh_docker

**Comment by kohlhase** [comment]
but in my case it is not.

**Comment by tkw1536** [comment]
Hmm, maybe it is related to another bug. (Weird because I am on master). I will investigate and get back to you once I know more.

**Comment by kohlhase** [comment]
BTW, I think you are on the wrong repos with this issue .

**Comment by tkw1536** [comment]
I don't think this is a problem anymore, closing.
