### ISSUE TITLE
lmh xhtml fails

### ISSUE THREAD

**Issue by m-iancu** [KWARC/localmh#204]
we renamed the mmt folder in deploy to main (so that we can have a script called mmt) a while back. It has probably been broken since.
Not sure where it is in the code but from lmh --simulate the following part is wrong: 
`/usr/bin/java -Xmx2048m -cp /var/data/localmh/ext/MMT/lib/*:/var/data/localmh/ext/MMT/mmt/branches/informal/*:/var/data/localmh/ext/MMT/lfcatalog/*:/var/data/localmh/ext/MMT/mmt/* info.kwarc.mmt.api.frontend.Run`  
You need to replace all `mmt` with `main`. i.e. the version below works for me:
`/usr/bin/java -Xmx2048m -cp /var/data/localmh/ext/MMT/lib/*:/var/data/localmh/ext/MMT/main/branches/informal/*:/var/data/localmh/ext/MMT/lfcatalog/*:/var/data/localmh/ext/MMT/main/* info.kwarc.mmt.api.frontend.Run`

Also, some forwarding of errors might be nice, localmh fails silently even though java reports class not found.

**Comment by tkw1536** [comment]
@m-iancu I am extremly busy atm. Feel free to fix the issue yourself. The code is at https://github.com/KWARC/localmh/blob/master/lmh/lib/mmt.py

**Comment by m-iancu** [comment]
fixed (on dev)
