### ISSUE TITLE
use xelatex instead of pdflatex for lmh pdf

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#209]
We have real unicode in SMGloM now (chinese), and it is difficult to make that work with ```pdflatex```
Maybe even better, make the LaTeX formatter configurable.

**Comment by kohlhase** [comment]
@angerhang @La-Stravaganza will be interested to know.

**Comment by tkw1536** [comment]
You can actually configure the executable to be used. If xelatex is installed inside the docker container, you can always do: 

```
lmh config env::pdflatex path_to_xelatex_executable
```

**Comment by kohlhase** [comment]
Ah great, I somehow did not see that configuration (I had actually looked for it). 
The path is ```/usr/local/texlive/2014/bin/x86_64-linux/xelatex``` or ````which xelatex```` can we make this the default?

**Comment by tkw1536** [comment]
Done.
