### ISSUE TITLE
Install new fonts inside lmh docker

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/localmh#217]
This is for fixing the problem with Chinese Module.
Testing Environment: Ubuntu 14.04 LTS 64-bits

Here is the full step:

1. Download the two fonts here: https://github.com/La-Stravaganza/sTeX/tree/265ec5c6418d79e514dd613fa0daa00cf2e49535/fonts 
 Both fonts are distributed with GPLv2 license, so we can use them.

2. Start lmh docker:
 ```
 lmh core start
 ```

3.  Put them in somewhere that we can find them inside docker, e.g.:
 ```
 ~/localmh/MathHub
 ```

4. Check the current fonts:

 ```
 fc-list
 ```

5. make directories for fonts:
 ```
 cd /usr/share/fonts/
 mkdir opentype
 cd opentype
 mkdir Fandol
 cd /usr/share/fonts/truetype/
 mkdir cwTeX
 ```

5. copy fonts to directories: (Suppose you store them under ~/localmh/MathHub)
 ```
 cd ~/localmh/MathHub
 cp FandolFang-Regular.otf /usr/share/fonts/opentype/Fandol/
 cp cwTeXQKai-Medium.ttf /usr/share/fonts/truetype/cwTeX/
```

6. cache fonts and check:
 ```
 fc-cache
 fc-list
 ```
 Now you should see this two new fonts are in the list

That's it!

Screenshots for generated pdf:

![selection_009](https://cloud.githubusercontent.com/assets/10081485/7144612/fcba5e1c-e2e6-11e4-8c5e-ee8104ab5127.png)

![selection_010](https://cloud.githubusercontent.com/assets/10081485/7144614/0150bf66-e2e7-11e4-87d1-0f6046d82cef.png)

**Comment by La-Stravaganza** [comment]
@kohlhase Plus, I need push rights to ``smglom`` to fix ``pre.zhs.tex`` and ``pre.zht.tex``, I've already made the changes on my own fork: https://gl.mathhub.info/jinzhang/sets/commit/ba6ef4ea8f849675565ad54444f21998c3c66e60

**Comment by kohlhase** [comment]
I gave you push rights.

**Comment by La-Stravaganza** [comment]
Done.

**Comment by tkw1536** [comment]
Fixed.
