### ISSUE TITLE
lmh seems to generate omdoc for all.*.tex again (on MathHub)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#222]
I am not sure whether this is a ```lmh``` or MathHub issue, but I suspect ```lmh```. There are error reports from generating OMDoc for ```all.en.tex``` and ```all.de.tex``` these should not be generated.

**Comment by kohlhase** [comment]
@m-iancu fyi

**Comment by m-iancu** [comment]
I use `lmh omdoc --all` to generate omdoc so I assume its an lmh issue.

**Comment by tkw1536** [comment]
should be fixed by MMT. Closing.
