### ISSUE TITLE
regression on Mac

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#229]
I am on lmh master and I get an error for ```lmh core start``` (and most other ```lmh``` commands). 

```
 cd -
/Users/kohlhase/localmh
Michaels-MacBook-Pro:localmh kohlhase$ git branch
  dev
* master
Michaels-MacBook-Pro:localmh kohlhase$ cd -
/Users/kohlhase/localmh/MathHub/MiKoMH/GenCS/source/dmath/en
Michaels-MacBook-Pro:en kohlhase$ lmh core start
An error occurred trying to connect: Post https://192.168.59.103:2376/v1.19/containers/create: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
docker: "inspect" requires a minimum of 1 argument.
See 'docker inspect --help'.

Usage: docker inspect [OPTIONS] CONTAINER|IMAGE [CONTAINER|IMAGE...]

Return low-level information on a container or image
An error occurred trying to connect: Post https://192.168.59.103:2376/v1.19/containers//bin/bash/exec: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
Michaels-MacBook-Pro:en kohlhase$ 
```

**Comment by tkw1536** [comment]
Several points: 

1. This is a localmh_docker issue. ```lmh core``` and all subcommands are provided by the wrapper script
2. Is boot2docker running? (```boot2docker status``` should say "running")
3. Can you run other docker commands? (try ```docker ps```, if that fails as well then your docker installation is broken)
4. What is the output of ```lmh core status``` ?

**Comment by kohlhase** [comment]
> This is a localmh_docker issue. lmh core and all subcommands are provided by the wrapper script
sorry, 
> Is boot2docker running? (boot2docker status should say "running")
yes. 
> Can you run other docker commands? (try docker ps, if that fails as well then your docker installation is broken)
```
Michaels-MBP:qed kohlhase$ boot2docker status
running
Michaels-MBP:qed kohlhase$ docker ps
An error occurred trying to connect: Get https://192.168.59.103:2376/v1.19/containers/json: x509: certificate is valid for 127.0.0.1, 10.0.2.15, not 192.168.59.103
Michaels-MBP:qed kohlhase$ 
```
> What is the output of lmh core status ?
```
 lmh core status
Container Id:   <none>
Dev directory: /Users/kohlhase/localmh
Currently in:   /Users/kohlhase/localmh/MathHub
Michaels-MBP:qed kohlhase$ 
```

**Comment by tkw1536** [comment]
@kohlhase You are experiencing a docker / boot2docker issue (I remember seeing it on one of their issue trackers)

I have committed an untested fix to the dev branch of localmh_docker, can you let me know if that one solves it for you?

**Comment by kohlhase** [comment]
no, it does not. But I still (after a reboot) have problems with ```docker ps```.

**Comment by tkw1536** [comment]
Fixed in localmh_docker master branch. 

To fix docker system wide, use something like: 

```bash
alias docker='docker --tlsverify=false'
```
in your .bashrc

**Comment by tkw1536** [comment]
Also, this problem should be fixed upstream with docker 1.7.1.

**Comment by kohlhase** [comment]
wonderful, thanks. works for me now.

**Comment by angerhang** [comment]
Nice! Upgrading to docker 1.7.1 also fixes this problem on my machine.

**Comment by tkw1536** [comment]
@kohlhase Docker 1.7.1 has been released it should work again. 

I have also reverted the workaround in localmh_docker
