### ISSUE TITLE
lmh sms seems to swallow \end{module}

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#233]
if it is not at the start to the line. See ```/path/to/localmh/MathHub/MiKoMH/GenCS/source/adt/en``` for an example

**Comment by kohlhase** [comment]
hmmm, that may also be an artefact of something else, I have updated, but run into different problems.

**Comment by cmaeder** [comment]
All my .sms files in that directory end with `\end{module}%`. (`tail -n 1 *.sms`)

**Comment by tkw1536** [comment]
@kohlhase Building is done only by MMT now, so it is their issue.

**Comment by kohlhase** [comment]
hmmm, I triggered it by ```lmh sms``` in the ```master``` branch.

**Comment by tkw1536** [comment]
that is entirely depracated now. I just merged with dev 5 minutes ago.

**Comment by kohlhase** [comment]
ok, I will retry.

**Comment by tkw1536** [comment]
@kohlhase You will have to 
```
lmh selfupdate
lmh core start
cd /path/to/localmh
rm -rf ext
lmh setup --install
exit
```
because MMT is now cloned via git.

**Comment by cmaeder** [comment]
I think this issue is obsolete and can be closed.
