### ISSUE TITLE
lmh pdf should honor -p (--pipe-worker-output)

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#243]
It seems that ```lmh pdf``` has lost the ```-p``` option. This should be reinstated (see the help text). Assigning to Tom for overview even though it is probably a MMT shortcoming @cmaeder

**Comment by tkw1536** [comment]
@kohlhase You are correct, it is an MMT issue. @cmaeder let me know once
you have an option that I can pass to MMT.

**Comment by cmaeder** [comment]
@kohlhase Currently, MMT always writes the output of the process to the file .pdflog. Is this option vital? So far the PdfLatexml plugin (as many others) does not take any options (most things are controlled by environment variables).

The easiest way to implement this for me would be via a (set or unset) environment variable.

**Comment by cmaeder** [comment]
I did not consider yet plugin arguments for my simplified (user-friendly) `rbuild` action.

**Comment by cmaeder** [comment]
I've added optional arguments. `rbuild pdflatex --pipe-worker-output <files>` does the job.
Alternatively, `--pipe-worker-output` may be  given at the end of an `extension` line. 

Only the long form is supported, file names starting with `--` are not supported, MMT does not show supported options.

@tkw1536 can you proceed?

**Comment by tkw1536** [comment]
Closing, since lmh gen now directly forwards to mmt.
