### ISSUE TITLE
mmt call

### ISSUE THREAD

**Issue by cmaeder** [KWARC/localmh#244]
In https://github.com/KWARC/localmh/blob/master/lmh/lib/modules/compile/targets.py
I see that PERL5LIB is set using "envvar". This is not respected by MMT. 
PERL5LIB (if set at all) must be set in the environment that calls MMT. (Maybe nothing special needs to be done for this to happen.)

In any case MMT always extends/sets PERL5LIB by/to the paths `/path/to/localmh/ext/perl5lib/lib/perl5:/path/to/localmh/ext/LaTeXML/blib/lib`.

For `pdflatex`  PERL5LIB should be irrelevant.

**Comment by cmaeder** [comment]
All other environment variables should become options for the `rbuild` target. You need to pass the options --force (before the target) and --pipe-worker-output (after the target) if applicable.

**Comment by cmaeder** [comment]
P.S. MMT does not emit any output if nothing needs to be rebuild. Should this be changed?

**Comment by cmaeder** [comment]
P.P.S MMT does now emit result messages on --clean and --onChange (the default), too. (--onChange even shows a `?` if the up-to-file has associated errors.)

**Comment by tkw1536** [comment]
No longer applies since lmh gen directly forwards to MMT now.
