### ISSUE TITLE
Add the --all option back

### ISSUE THREAD

**Issue by m-iancu** [KWARC/localmh#247]
We can still achieve it by giving the lmh mathhub path but that can differ from system to system (docker to non-docker setup) so it's hard to script. It's also sufficient for me if there is a good way to get the path to the lmh mathhub directory.

**Comment by tkw1536** [comment]
For everything then ```lmh gen``` the option still exists. Since that is now an alias of ```mmt rbuild``` please make an MMT issue if you want the --all option back for that command.
