### ISSUE TITLE
lmh pdf *.tex up-to-date detection bug

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/localmh#249]
Current detection only cares about the source file *.tex.
After I manually deleted the generated pdf file, and hope to generate a new version(after I changed something in sTeX), this doesn't work. Every time I run a single test case, I have to edit this test case and make it not "up-to-date".

**Comment by tkw1536** [comment]
This is now an MMT issue because MMT does all building. Please re-create this issue there if still applicable.
