### ISSUE TITLE
smglom/meta-inf is necessary for any modules in smglom

### ISSUE THREAD

**Issue by La-Stravaganza** [KWARC/localmh#250]
smglom/meta-inf should be a dependency for any modules in smglom. ``lmh selfupdate`` doesn't manage to solve this currently.

**Comment by angerhang** [comment]
I had the same problem.

In your `MathHub` directory do the following:
```
rm -rf smglom
lmh install smglom
```

**Comment by tkw1536** [comment]
It if is in META-INF/MANIFEST.MF ```lmh install smglom``` should install it automatically. I can also hard-code that if a repository "group/meta-inf" exists that it should automatically be installed along with any repository group.

**Comment by kohlhase** [comment]
I think that would be a good idea.

**Comment by tkw1536** [comment]
All "lmh install" related commands now treat the meta-inf repository of a repository as a dependency even if it is not explicitly mentioned in any MANIFEST.MF file. lmh update should thus install any missing repositories.
