### ISSUE TITLE
lmh * --help talks about rbuild

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#253]
the help text generated talks about ```rbuild```. That should be changed somehow (e.g. by having a help option that replaces commands) or there should be a preamble added by ```lmh``` that says something like 
```
lmh <target> <rest> 
maps to 
mmt rbuild <target> <rest> 
So understand the mmt rbuild help text accordingly. 
```

**Comment by kohlhase** [comment]
@cmaeder should also brainstorm about this.

**Comment by tkw1536** [comment]
1) This only affects ```lmh gen``` related commands. 
2) A solution is to make the ```mmt rbuild``` help aware of the current target.

**Comment by cmaeder** [comment]
`lmh mmt rbuild --help` displays help for rbuild. (The help text is identical for the lmh aliases, i.e. `lmh omdoc --help`)
