### ISSUE TITLE
lmh gen alltex does not work 

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#255]
It does not seem to do anything on my computer 
```
Michaels-MacBook-Pro:en kohlhase$ pwd
/Users/kohlhase/localmh/MathHub/MiKoMH/GenCS-problems/source/SML/en
Michaels-MacBook-Pro:en kohlhase$ lmh gen alltex
Michaels-MacBook-Pro:en kohlhase$ ls -l all.tex
ls: all.tex: No such file or directory
```
probably a MMT problem, but @tkw1536 should have a look as well.

**Comment by cmaeder** [comment]
Could you try to add a directory argument: `lmh gen alltex .`

**Comment by kohlhase** [comment]
ah, that gives results
```
 lmh gen alltex .
error: alltex: GenCS-problems/source/SML/en/cart-casc-prob.tex missing: smglom/smglom/source/converse-relation.tex
alltex-result: success GenCS-problems/source/SML/en/all.tex
```
I guess I have to clean up my source :-)

**Comment by cmaeder** [comment]
The "error" is just a missing dependency

**Comment by kohlhase** [comment]
Yes, I know, I am fixing them as we speak.


On 12/10/15 09:19, cmaeder wrote:
>
> The "error" is just a missing dependency
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KWARC/localmh/issues/255#issuecomment-147309693>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by cmaeder** [comment]
Meanwhile `lmh gen alltex` should work everywhere see https://github.com/KWARC/MMT/issues/75 and https://github.com/KWARC/MMT/commit/a8419b194da630b2dbc1220cd4e1c41e21cefeb8. 
Therefore I close this.
