### ISSUE TITLE
latexml: java.nio.charset.MalformedInputException: Input length = 1

### ISSUE THREAD

**Issue by angerhang** [KWARC/localmh#256]
On MathHub, we have 2000+ documents that contain the error 
```
 latexml: java.nio.charset.MalformedInputException: Input length = 1
```
https://mathhub.info/smglom/algebra/ideal.omdoc.

The ad48f4fb7d79339e98ad2158eae6cc48bbb7b7ea commit perhaps didn't fix the encoding properly. 
This needs to fixed, before we can generate any omdoc document.

**Comment by m-iancu** [comment]
MathHub data was a bit old. After the latest updates and a rerun (just finished) there are only 19 such errors left (before were ~2000 indeed).

**Comment by angerhang** [comment]
I see. I had similar errors in my local repository too, but after the update, everything seems to be fine now.
