### ISSUE TITLE
sTeX changes not effective unless restart docker

### ISSUE THREAD

**Issue by angerhang** [KWARC/localmh#259]
I have found out this situation occurs multiple times today. Might have been caused by preloading?

If I change something in a sTeX binding, and do `lmh omdoc` the changes are effective, but after I change the binding again and do `lmh omdoc` again the newly generated files are affected by the new changes to the binding unless I do:
```
lmh docker stop
lmh docker start
```

I think lmh is not reloading all the bindings that have been changed.

**Comment by kohlhase** [comment]
yes, you are right. When you run ```latexmlc```, it starts a ```latexmls``` server, which stays alive (I think for 600s on default) and in particular does not reload. You want to either start ```latexmlc``` with a smaller timeout (so that the server dies from alone) or you want to kill the ```latexmls``` proceses, e.g. with ```pkill latexmls```.

**Comment by angerhang** [comment]
Now I understand. Thanks.
