### ISSUE TITLE
Instate lmh 'xml'? 

### ISSUE THREAD

**Issue by angerhang** [KWARC/localmh#271]
As Deyan pointed out in https://github.com/KWARC/sTeX/issues/190, I think it would be helpful if we have a command 'lmh xml' that only generates `*.xml` without calling the post-processor for debugging purposes.

**Comment by kohlhase** [comment]
Indeed, that is a good thing to have, but you should really direct this in the MMT issue tracker at https://github.com/KWARC/MMT/issues, since that takes care of the building now.

**Comment by angerhang** [comment]
Move to MMT issue tracker.
