### ISSUE TITLE
clock skew in docker

### ISSUE THREAD

**Issue by kohlhase** [KWARC/localmh#305]
upon an ```lmh setup --update``` I get 
```
Appending installation info to /mounted/lmh/ext/perl5lib/lib/perl5/x86_64-linux-gnu-thread-multi/perllocal.pod
make: warning:  Clock skew detected.  Your build may be incomplete.
OK
```
I assume it is a clock in the docker machine, is there something I can do about that?

**Comment by kohlhase** [comment]
are we running ```ntp``` on the docker? That might be a good idea if not. I tried 
```
pt-get install install ntp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package install
E: Unable to locate package ntp
```
so that did not work.

**Comment by tkw1536** [comment]
This is a known issue in boot2docker / docker-machine on mac. When the mac is put to sleep, the macs clock continues to tick, the VMs clock does not. For now restarting the VM should help: ```docker-machine restart default```. It also sounds like they are working on a fix upstream.

**Comment by kohlhase** [comment]
ah, OK, then I will wait.
